name: Publish Doxygen XML

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz zip

      - name: Build Doxygen XML
        run: |
          doxygen project/doxygen/Doxyfile
          cd doc/doxygen
          zip -r ../../doxygen-xml-${{ github.ref_name }}.zip xml
          cd ../../

      - name: Delete existing release (if any)
        continue-on-error: true
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ github.ref_name }} -y --cleanup-tag || true

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: doxygen-xml-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
